FROM --platform=amd64 ubuntu:jammy

# update packages
RUN apt-get update && apt-get upgrade -y

# install packages
RUN apt-get install -y sudo git ssh tmux htop zsh locales

# clean up
RUN rm -rf /var/lib/apt/lists/

# locales
RUN locale-gen en_US.UTF-8 && update-locale LANG=en_US.UTF-8

# create user
ENV USER work
RUN adduser --quiet --disabled-password --shell /bin/zsh ${USER}
RUN echo "${USER} ALL=(ALL:ALL) NOPASSWD: ALL" > /etc/sudoers.d/${USER}
USER ${USER}
RUN touch /home/${USER}/.zshrc