name: Build Base Images
on:
  workflow_dispatch:
  push:
    branches:
      - main
env:
  REGISTRY: docker.io
  IMAGE_NAME: raptium/dev-base
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@79abd3f86f79a9d68a23c75a09a9a85889262adf
      - name: Log into registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@28218f9b04b4f3f62068d7b6ce6ca5b26e35336c
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Extract Docker metadata (Ubuntu LTS)
        id: meta-ubuntu-lts
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=schedule,prefix=ubuntu-lts-
            type=ref,event=branch,prefix=ubuntu-lts-
            type=ref,event=tag,prefix=ubuntu-lts-
            type=ref,event=pr,prefix=ubuntu-lts-
            type=ref,event=pr,prefix=ubuntu-lts-
            type=semver,pattern={{version}},prefix=ubuntu-lts-
            type=sha
      - name: Build and Push (Ubuntu LTS)
        uses: docker/build-push-action@ac9327eae2b366085ac7f6a2d02df8aa8ead720a
        with:
          context: ./base-images
          file: ./base-images/Dockerfile.ubuntu-lts
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta-ubuntu-lts.outputs.tags }}
          labels: ${{ steps.meta-ubuntu-lts.outputs.labels }}